# Form implementation generated from reading ui file 'parse_wizard_2.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class WizardSecondPageUi:

    def setupUi(self, SecondPage):
        SecondPage.setObjectName("SecondPage")
        SecondPage.resize(436, 411)
        self.gridLayout = QtWidgets.QGridLayout(SecondPage)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(SecondPage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.UserUrls = QtWidgets.QPlainTextEdit(SecondPage)
        self.UserUrls.setObjectName("UserUrls")
        self.gridLayout.addWidget(self.UserUrls, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(209, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CancelButton = QtWidgets.QPushButton(SecondPage)
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout.addWidget(self.CancelButton)
        self.OkButton = QtWidgets.QPushButton(SecondPage)
        self.OkButton.setObjectName("OkButton")
        self.horizontalLayout.addWidget(self.OkButton)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)

        self.retranslateUi(SecondPage)
        QtCore.QMetaObject.connectSlotsByName(SecondPage)

    def retranslateUi(self, SecondPage):
        _translate = QtCore.QCoreApplication.translate
        SecondPage.setWindowTitle(_translate("SecondPage", "Parsing wizard"))
        self.label.setText(_translate("SecondPage", "Insert your urls to pages:"))
        self.CancelButton.setText(_translate("SecondPage", "Cancel"))
        self.OkButton.setText(_translate("SecondPage", "OK"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     SecondPage = QtWidgets.QWidget()
#     ui = WizardSecondPageUi()
#     ui.setupUi(SecondPage)
#     SecondPage.show()
#     sys.exit(app.exec())
